### ISSUE TITLE
[JPHP RFC]: Remove array keyword

### ISSUE THREAD

**Issue by SerafimArts** [jphp-compiler/jphp#172]
Remove array keyword
----------------

- Version: 1
- Date: 19.02.2015
- Author: Kirill nesk@xakep.ru
- Status: Draft

### Introduction

Currently, the keyword "array" is potentially deprecated and currently hardly used. Starting with version php 5.4 is available a new way of creating arrays `[]` аnd version 5.4 is the oldest (oldest stable) version. It is necessary to get rid of the remnants of the past, given the almost compatible API - it does not take very many problems.

###  Proposal

Remove the use of `array(...)` as an announcement arrays.

### Backward Incompatible Changes

The keyword `array` will not work anymore, but it can be returned by a PHP-code fix:
```php
function array() { return func_get_args(); }
```

### Total

- This class ([php\lib\items](https://github.com/jphp-compiler/jphp/blob/master/jphp-runtime/src/main/resources/JPHP-INF/sdk/php/lib/items.php)) can be renamed to `php\lib\array`. 
- You can use `array` as namespace name (inside helpers, as example)
- Will result in some of the language in order.

Currently behavior will be fixed:
```php
<?php
class string {}    // OK
class int {}       // OK
class float {}     // OK
class double {}    // OK
class bool {}      // OK
class object {}    // OK
class null {}      // OK
class array {}     // now: ERROR, with rfc: OK
```
```php
<?php
function string() {} // OK
function int() {}    // OK
function float() {}  // OK
function double() {} // OK
function bool() {}   // OK
function object() {} // OK
function null() {}   // OK
function array() {}  // now: ERROR, with rfc: OK
```
```php
<?php
namespace string {} // OK
namespace int {}    // OK
namespace float {}  // OK
namespace double {} // OK
namespace bool {}   // OK
namespace object {} // OK
namespace null {}   // OK
namespace array {}  // now: ERROR, with rfc: OK
```

Propose to speak in the comments: **yes** \ **no**
*Preferably with a detailed view*

**Comment by dim-s** [comment]
What about `array(key => value)` if array will be a function?

**Comment by SerafimArts** [comment]
Idea\phpStorm => Ctrl+Alt+L (with force  `[]` option). I cant see other cases =(

**Comment by SerafimArts** [comment]
Hmmm.... https://wiki.php.net/rfc/context_sensitive_lexer

**Comment by SerafimArts** [comment]
Я буду скучать по тебе, мой идеальный мир Т_Т

**Comment by dim-s** [comment]
Будет реализовано, когда выйдет PHP 7.
