### ISSUE TITLE
Can we add JAVA lib?

### ISSUE THREAD

**Issue by Hetarnam** [jphp-compiler/jphp#177]
Hi !

I just discover this repos but i have one question, we can add JAVA library on it? 
Because i want to use IO Session so is that possible?

Thanks you!

**Comment by SerafimArts** [comment]
Hmm. What about this? [https://github.com/jphp-compiler/jphp/wiki/For-Contributors](https://github.com/jphp-compiler/jphp/wiki/For-Contributors)

**Comment by Hetarnam** [comment]
Perfect, we can i think so :)
