### ISSUE TITLE
[API] Add class NotImplementedException

### ISSUE THREAD

**Issue by SerafimArts** [jphp-compiler/jphp#192]
subj

**Comment by maxbaldin** [comment]
Php has those built-in exceptions:
```php
    BadFunctionCallException
    BadMethodCallException
    DomainException
    InvalidArgumentException
    LengthException
    LogicException
    OutOfBoundsException
    OutOfRangeException
    OverflowException
    RangeException
    RuntimeException
    UnderflowException
    UnexpectedValueException
```

Why not write
```php
class NotImplementedException extends Exception{
    
}
```
for your purpose?

(github examples: https://github.com/search?l=php&q=NotImplementedException&ref=searchresults&type=Code&utf8=%E2%9C%93 )

**Comment by SerafimArts** [comment]
This is default: 
1) Exception for .NET
2) Constant for Python (`NotImplemented`)
3) Http code (501)
4) Ruby class: (`NotImplementedError`)
5) Scala error (`NotImplementedError`)
6) Java exception (`NotImplementedException`) *inside apache commons

I think this exception must implemented inside jphp core.
