### ISSUE TITLE
Is it possible to use Scala libraries from within jphp?

### ISSUE THREAD

**Issue by pqr** [jphp-compiler/jphp#197]
Is it possible to use Scala libraries from within jphp?
If yes, could you please show a small interop example?

**Comment by dim-s** [comment]
I think yes. To do that, you need to create a class that extends `php.runtime.ext.support.Extension` and need to write a wrapper class like shown [here](https://github.com/jphp-compiler/jphp/wiki/Extension-BaseObject-class) only via Scala.

**Comment by dim-s** [comment]
Later, I will add an example with Scala.
