### ISSUE TITLE
Require & include bug

### ISSUE THREAD

**Issue by devinterx** [jphp-compiler/jphp#198]
```
require __DIR__ . '//engine/Vergo.php'; - working
```
But:
```
require __DIR__ . '/engine/Vergo.php';
```
> Fatal error: Uncaught exception 'EngineException' with message 'require(): Failed opening required 'res:/engine/Vergo.php'' in res://Bootstrap.php on line 3, position 1

res: mayby lost slashes? res://

**Comment by dim-s** [comment]
This is a specific bug, will be fixed.

**Comment by dim-s** [comment]
Can you write the result of `var_dump(__DIR__ . "/engine/Vergo.php");`?

**Comment by SerafimArts** [comment]
> Vanga mode enabled
`string(...) res:/engine/Vergo.php`
> Vanga mode disabled

=)

**Comment by dim-s** [comment]
I cannot repeat this bug =(

**Comment by devinterx** [comment]
Yes
> string(21) "res:/engine/Vergo.php"

http://joxi.ru/DmBXyXbIygl0AP

**Comment by dim-s** [comment]
__DIR__ of file that included from resources directories (`res://` protocol) must be `res://`, but it equals to `res:`. It will be fixed to `res://` and you can include via `require __DIR__ . '/engine/Vergo.php'`. That will be equivalent to `include 'res://engine/Vergo.php'`.

**Comment by devinterx** [comment]
Means we will wait, thanks.
