### ISSUE TITLE
PHP function exec()

### ISSUE THREAD

**Issue by devinterx** [jphp-compiler/jphp#199]
Please, add the function **exec()**

**Comment by SerafimArts** [comment]
1) https://github.com/jphp-compiler/jphp/wiki/Migration-Guide
> One of the project goals is:
> Replacing the ugly runtime library of Zend PHP with a better runtime library.

2) http://jphp-docs.readthedocs.org/en/latest/api_en/php/lang/Process/
```
$p = (new php\lang\Process('.....'))->start();
```

**Comment by devinterx** [comment]
Thanks for the help
