### ISSUE TITLE
Illegal characters in the URL

### ISSUE THREAD

**Issue by FirestarterUA** [jphp-compiler/jphp#205]
Hello. I try to get page from Url thruout 
```
Jsoup::connect($link)->get() 
```
or
```
Stream::getContents($link)
```
But most of links execute ioExeption that "illegal characters in the URL".
As i understand we can not work with http withuout URLEncoder.encode URLEncoder.decode methods?
We need to add java.net.URLEncoder to jphp code?
Please help to include JAVA class to JPHP code. Thanks.

**Comment by dim-s** [comment]
Please, execute `var_dump($link)` and write the result here. $link contains invalid characters for url.

**Comment by FirestarterUA** [comment]
Code like this:
```
$cwd = System::getEnv()['DIRNAME'];

$links = Stream::of($cwd.'forums.txt', 'r');

try {
   	$link = $links->readFully();   
    $content = Stream::getContents($link);
    Stream::putContents($cwd.'forums2.txt', $content, 'a');
} finally {
   $links->close();
}
```
````
http://www.wwlf.h10.ru/
http://planeta-malysh.ru/forum/
http://heelys-portugal.com/forum/
http://galeclub.invisionplus.net/
http://profikkm.ru/forum/
http://it19.invisionplus.net/
http://mystateline.com/forums/
http://sepecat.info/forum/
http://forum.paintwar.ru/
http://nuavongtraidat.com/4rum/
http://forum.rostov-smu.ru/
http://tmprint.spb.ru/forum/
````

**Comment by dim-s** [comment]
The $link variable contains the all urls from `froms.text`, the http functions cannot get content from multiple urls.

**Comment by FirestarterUA** [comment]
$links->readFully(); read's all file? 

Дмитрий, простите за тупые вопросы. Но очень хочеться разобраться.

**Comment by dim-s** [comment]
Use the scanner class to read each line from file.

```php
use php\util\Scanner;
...
$scanner = new Scanner($links);

while ($scanner->hasNextLine()) {
    $url = $scanner->nextLine();
    // .... working with each url
}
```

**Comment by dim-s** [comment]
readFully читает абсолютно все что есть в файле, т.е. весь файл.
