### ISSUE TITLE
[BUG\Feature] ReflectionClass::getDocComment

### ISSUE THREAD

**Issue by SerafimArts** [jphp-compiler/jphp#207]
Example:
```php
/**
 * Class Some
 * @Some("Test")
 */
class Some
{
}

echo (new ReflectionClass(Some::class))->getDocComment();
```

jphp: 0.6.11
```php

Class Some
@Some("Test")

```

php: 5.6 x86 TS
```php
/**
 * Class Some
 * @Some("Test")
 */
```

Propose: Save currently behavior, but;
- Move `\ReflectionSome` classes to `php\reflection\ReflectionSome`
- Add `class ReflectionSome extends \php\reflection\ReflectionSome {}` inside `Zend Extension` and override required methods behavior.

**Comment by dim-s** [comment]
:+1: Good idea =)

**Comment by SerafimArts** [comment]
Ok. I can to do this.
