### ISSUE TITLE
[enhancement] 0.7 String functions

### ISSUE THREAD

**Issue by SerafimArts** [jphp-compiler/jphp#209]
### `::contains`

Searches for all substrings and returns `true` if substring was found.

```php
String::contains(string $subject, string $needle); // bool

// Actual
!(String::pos(string $subject, string $needle) === -1);
```

### `::containsCount`

Searches for all substring and returns the number of occurrences of a subject.

```php
String::containsCount(string $subject, string $needle); // int

// Actual
substr_count(string $subject, string $needle);
```

### `::format`

Format string by pattern: [http://php.net/SprintF](http://php.net/SprintF)

```php
String::format(string $subject, mixed ...$args); // string

// Actual
sprintf(string $subject, mixed ...$args);
```

### `::upperFirst`

Change first character case to upper

```php
String::upperFirst(string $subject); // string

// Actual
ucfirst(string $subject);
```

### `::lowerFirst`

Change first character case to lower

```php
String::lowerFirst(string $subject); // string

// Actual
ucfirst(string $subject);
```

**Comment by dim-s** [comment]
I think that `String::count` is better than `String::containtsCount`, like in Ruby and Python.

**Comment by SerafimArts** [comment]
I thought it was the name of the (`containtsCount`) should be similar to `contains`, as they have similar functionality.
