### ISSUE TITLE
Make use of new Java 8 API features

### ISSUE THREAD

**Issue by quipsy-karg** [jphp-compiler/jphp#211]
It is impressive to see benchmark results of your project. You can gain even higher performance by utilitzing the API features new to Java 8. I benchmarked one of them as-is with the result described on my blog https://headcrashing.wordpress.com/2015/04/04/foreach-vs-for/, but the real benefit is that future improvements of the JRE itself will automatically speed up your code then without touching it. :-)

**Comment by SerafimArts** [comment]
Sad that can not maintain the original 1.8. Android.... =(
