### ISSUE TITLE
Can not use base64_encode/decode or pack/unpack function in jphp, right?

### ISSUE THREAD

**Issue by faof** [jphp-compiler/jphp#222]
I want to know whether jphp support all of the php functions.
So I write code like this:

Launcher launcher = new Launcher(args);
launcher.run();
CompileScope scope = launcher.getCompileScope();
Set<String> methods = scope.getFunctionMap().keySet();
methods.stream().forEach(System.out::println);

I didn't see base64_encode/decode or pack/unpack function.
So I can't use these functions in jphp, right?
And if I can't do this now in the version 0.71, how can I implement these functions as a patch?

**Comment by dim-s** [comment]
See here: https://github.com/jphp-compiler/jphp/pull/164

You can implement these functions for Zend extension like the pull request.

**Comment by faof** [comment]
OK, thx
