### ISSUE TITLE
Input line too long when using generated bat file

### ISSUE THREAD

**Issue by DanielRuf** [jphp-compiler/jphp#223]
The long `set CLASSPATH` line in the generated bat file throws an error on Windows.

Tested on Windows 7 64bit

**Comment by dim-s** [comment]
You can try to install Gradle and use the `gradle` command instead of `gradlew.bat`

**Comment by DanielRuf** [comment]
Sure, but at the moment there is some documentation missing when we do not use Gradle.

Also you write `Recommended, not necessary: Gradle`
https://github.com/jphp-compiler/jphp/wiki/Installation

**Comment by dim-s** [comment]
What version of gradle are you using? Required 2.+

**Comment by DanielRuf** [comment]
I use the linked Gradle version (2.3) ;-)

Anyway,I got it working.

Just replaced the very long line `set CLASSPATH= ...` with `set CLASSPATH=%APP_HOME%\lib\*;` ;-)

**Comment by dim-s** [comment]
Do you want to build the core of jphp or only try to run a php script?

**Comment by DanielRuf** [comment]
Run a PHP, but it works now. 

I just use gradle to retrieve and build the sources from the repository (the jar files) and create the files needed for running the bat file.

After this I can directly use the bat file without any problems. The PHP fileis now executed,after I have changed the long line to the short version in the bat file.

Because this produces the `Input line too long` error on Windows.

**Comment by dim-s** [comment]
It looks like a bug of the Gradle System and its `wrapper` task that creates gradlew files.

**Comment by DanielRuf** [comment]
Right, it seems Gradle generates a line with all libraries instead of using an asterisk as placeholder and the issue 2292 is still open, but there are plenty workarounds. 

Maybe we can mention this in the Wiki, if other developers and users face the same problem.

https://discuss.gradle.org/t/gradle-application-plugin-and-cmd-exe-line-size-limitations/2521/18
https://issues.gradle.org/browse/GRADLE-2992
http://stackoverflow.com/questions/32088966/gradle-generated-startscript-for-windows-produces-input-line-is-too-long
