### ISSUE TITLE
How can we process files line by line?

### ISSUE THREAD

**Issue by DanielRuf** [jphp-compiler/jphp#224]
Normally we read line by line into memory using `fgets` and `stream_get_line`.

In the WIki there is mentioned, that we have to use the `Stream` class.

But this does not have any method for reading line by line.

How can we do this with JPHP? This is not quite clear.

Or do you suggest reading a whole (big) file directly into the memory and parsing thisline by line?

**Comment by dim-s** [comment]
Yes, you can do it via the Scanner class, for example:
http://jphp-docs.readthedocs.org/en/latest/api_en/php/util/Scanner/


```php
use php\util\Scanner;
use php\io\Stream;

$stream = Stream::of('path/to/file');

try {
     $scanner = new Scanner($stream, 'UTF-8');
 
     while ($scanner->hasNextLine()) {
            $line = $scanner->nextLine();
            var_dump($line);
     }
} finally {
     $stream->close();
}
```

**Comment by DanielRuf** [comment]
Ah ok, thanks for the clarification.

Because the Wiki did not mention this, that we can also use the Scanner class for files in addition to the Stream classes.

https://github.com/jphp-compiler/jphp/wiki/Files-and-Streams

So we can use this Scanner class like we do in Java.
I thought there are methods like fgets and stream_get_line which use the Scanner class under the hood and did not see the Scanner class but the Stream classes.

**Comment by dim-s** [comment]
I'll add it to our Wiki =) Maybe we need to add a new method to the Stream class - readLine() which uses the Scanner class.

**Comment by DanielRuf** [comment]
This would be very helpful and ease the use when it becomes part of the Stream class.
