### ISSUE TITLE
disable hikaricp console output

### ISSUE THREAD

**Issue by BurakDev** [jphp-compiler/jphp#228]
Hello, there is any way to disable hikariCP console output ?

Thanks !

![hikari](https://cloud.githubusercontent.com/assets/3963184/11148227/bb03a4d8-8a1b-11e5-8826-cd59c40dd402.png)

**Comment by dim-s** [comment]
HikariCP uses the log4j library for loging, try put a file into the `src` directory of  your project:

`log4j.properties`

```
log4j.logging.com.zaxxer.hikari=warn
```

**Comment by BurakDev** [comment]
I still have the DEBUG output :cry:

**Comment by dim-s** [comment]
Ok, I found a similar issue http://stackoverflow.com/questions/27274115/disable-hikaripool-logging

I'll disable the all debug messages from HikariCP in the next minor version of jphp.

**Comment by BurakDev** [comment]
Maybe the debug messages is useful for some developpers, you can't create a PHP method to enable/disable debug ?

**Comment by BurakDev** [comment]
Same issue about WebServer, we have Spring log.

**Comment by BurakDev** [comment]
@dim-s When I use WebServer and MySQL the DEBUG output is disabled

**Comment by dim-s** [comment]
@BurakDev 
I am glad that you have found a temporary solution.

I think Spring has a log configuration in its resources which disables debug messages.
