### ISSUE TITLE
How to RUN Joomla 3 in Jphp??

### ISSUE THREAD

**Issue by gencube** [jphp-compiler/jphp#230]
Hi,

I am new to JPHP, anyone here had successfully ran Joomla/SugarCRM/Drupal using JPHP?

https://www.joomla.org/download.html

If yes, kindly shown the how to or provide an example for such.

**Comment by SerafimArts** [comment]
Just implements the missing features (functions) of php core. 

P.S. Zend core api (https://github.com/jphp-compiler/jphp/tree/master/jphp-zend-ext) is deprecated now. Its a new language.

**Comment by jkeks** [comment]
jphp and php not compatible. Better compare jphp with java

**Comment by dim-s** [comment]
See here: http://j-php.net/faq/

**Comment by gencube** [comment]
Another missing the mark project. No wonder the adoption rate is so low. The above mentioned projects are majority codes in the php community.
