### ISSUE TITLE
JPHP build from source on ARM

### ISSUE THREAD

**Issue by kkeker** [jphp-compiler/jphp#231]
Hello!

I use the computer ODROID-XU4, he is running Ubuntu 14 processor ARM, so I do not fit your finished binary file, how can I put together a system from source?

**Comment by dim-s** [comment]
If you want to build jphp from sources you should install and use Gradle on your system. Then you should build and install jphp artifacts to your maven local repository via `gradle install` (in the root of the sources). Then follow the instructions from the "Get Started" article, but before you should add maven local repository in the `build.gradle` file:

```
repositories {
    mavenLocal();
    jcenter()
    mavenCentral()
}
```

That should work.

**Comment by kkeker** [comment]
root@odroid-server:~/jphp-get-started# mvn -V
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.8.0_65
Java home: /usr/local/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux" version: "3.10.82" arch: "arm" Family: "unix"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO]

You must specify at least one goal or lifecycle phase to perform build steps.
The following list illustrates some commonly used build commands:

  mvn clean
    Deletes any build output (e.g. class files or JARs).
  mvn test
    Runs the unit tests for the project.
  mvn install
    Copies the project artifacts into your local repository.
  mvn deploy
    Copies the project artifacts into the remote repository.
  mvn site
    Creates project documentation (e.g. reports or Javadoc).

Please see
http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
for a complete description of available lifecycle phases.

Use "mvn --help" to show general usage information about Maven's command line.


[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Jan 21 23:39:25 MSK 2016
[INFO] Final Memory: 3M/15M
[INFO] ------------------------------------------------------------------------


root@odroid-server:~/jphp-get-started# gradle -v

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_91 (Oracle Corporation 24.91-b01)
OS: Linux 3.10.82 arm


root@odroid-server:~/jphp-get-started# ls
build.gradle  debug.conf  gradle  gradlew  gradlew.bat  src
root@odroid-server:~/jphp-get-started# cat build.gradle
apply plugin: 'application'

repositories {
    jcenter()
    mavenCentral()
}

sourceSets {
    main.resources.srcDirs = ['src']
}

dependencies {
    compile 'org.develnext:jphp-core:0.7+' // include jphp with runtime and compiler

    compile 'org.develnext:jphp-zend-ext:0.7+' // legacy zend classes and functions
    compile 'org.develnext:jphp-json-ext:0.7+' // json support
    compile 'org.develnext:jphp-xml-ext:0.7+' // xml library
    compile 'org.develnext:jphp-gdx-ext:0.7+' // libgdx wrapper
    compile 'org.develnext:jphp-jsoup-ext:0.7+' // library for site parsing in jQuery style
    compile 'org.develnext:jphp-mail-ext:0.7+' // for sending mail via smtp
    compile 'org.develnext:jphp-webserver-ext:0.7+' // embedded http web server
    compile 'org.develnext:jphp-sql-ext:0.7+' // for working with SQL databases, like PDO and JDBC
    compile 'org.develnext:jphp-swing-ext:0.7+' // GUI library based on Swing

    compile 'org.develnext:jphp-debugger:0.7+' // JPHP debugger (xdebug)
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.4'
}

run {
    mainClassName = 'php.runtime.launcher.Launcher'
    jvmArgs += ["-Dfile.encoding=UTF-8"]
}

task debug(dependsOn: run.dependsOn) {
    doFirst {
        run.jvmArgs += ["-Djphp.debug=true", "-Djphp.config=debug.conf"]
        run.execute()
    }
}root@odroid-server:~/jphp-get-started# gradle run

FAILURE: Build failed with an exception.

* Where:
Build file '/root/jphp-get-started/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating root project 'jphp-get-started'.
> Could not find method jcenter() for arguments [] on root project 'jphp-get-started'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.688 secs

**Comment by kkeker** [comment]
Excuse me, I have the above invalid parameter display information about the version of Maven.

root@odroid-server:~/jphp-get-started# mvn -v
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.8.0_65
Java home: /usr/local/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux" version: "3.10.82" arch: "arm" Family: "unix"

**Comment by dim-s** [comment]
Please, use Gradle 2.0 and greater ...

**Comment by dim-s** [comment]
And replace the all dependencies like:

`org.develnext:jphp-zend-ext:0.7+` -> `org.develnext:jphp-zend-ext:0.7.1-SNAPSHOT`
