### ISSUE TITLE
Basic android tutorials

### ISSUE THREAD

**Issue by razzbee** [jphp-compiler/jphp#235]
Hello , is there any info on how to test android development using jphp ? I would be very glad to do a test app.

**Comment by Craftist** [comment]
jphp is not for android how, wait for end of autumn, then will be normal android support.

**Comment by razzbee** [comment]
Good, I am sure this will be a big turn around for PHP , Thanx

**Comment by MuhammadMuneeb** [comment]
Is there any update on this? I would love to try it out
