### ISSUE TITLE
Enum'ы

### ISSUE THREAD

**Issue by Craftist** [jphp-compiler/jphp#236]
Добавить enum'ы в jphp.
Синтаксис:
```php
enum ColorsEnum
{
RED, GREEN, BLUE, YELLOW
}

$colors = ColorsEnum::RED;
if ($colors == ColorsEnum::RED) echo '$colors is ColorsEnum::RED';
```
Желательно с typehinting'ом в функциях:
```php
function setColor(ColorsEnum $ce)
{
$this->color = $ce;
}
```
То есть если в $ce зададут не ColorsEnum, то произойдет ошибка.
Это здорово расширит ООП jphp.

**Comment by SerafimArts** [comment]
P.S. https://wiki.php.net/rfc/enum

**Comment by dim-s** [comment]
В PHP официальном не приняли пока не приняли такую фичу, мы не будем лишний раз усложнять язык и делать его другим, если на то пошло, уж лучше сразу писать с нуля другой язык.
