### ISSUE TITLE
Example usage of JPHP as Scripting Language of a Java App?

### ISSUE THREAD

**Issue by diamantisk** [jphp-compiler/jphp#237]
Hello,

First of all accept my congratulations for your project. 
I wonder if and who i can use this version of php as a scripting language of a java based application (in order to allow users to add functionality to this application). If yes, it is possible to provide us a minimal example of this?

Thank you

**Comment by dim-s** [comment]
```java
import php.runtime.env.*;

CompileScope scope = new CompileScope();
Environment env = new ConcurrentEnvironment();

ModuleEntity phpModule = env.importModule(new Context(new File('path/to/file.php')));
Memory result = phpModule.include(env);

System.out.println(result);
```

`path/to/file.php`:
```php
$var = "Hello World";

return $var;
```

Also you can create a Context instance for InputStreams or simple php code (see constructors of the Context class).
