### ISSUE TITLE
Use jphp as dependency package?

### ISSUE THREAD

**Issue by bonndan** [jphp-compiler/jphp#238]
Hi,

is it possible to use jhp as depency? I am working on a php to groovy transpiler and having a library that executes builtin php functions would be very handy. For instance, I would import your json stuff and magically calling json_encode() works (being executed in Java?).

Or did I get things completely wrong?

Thanks

Daniel

**Comment by dim-s** [comment]
Yes, use maven http://j-php.net/download/ dependencies, for json is `jphp-json-ext`, for zend std is `jphp-zend-ext`. `jphp-runtime` also has basic functions from php. 

For instance, the string php functions can be used via this class: https://github.com/jphp-compiler/jphp/blob/master/jphp-zend-ext/src/main/java/org/develnext/jphp/zend/ext/standard/StringFunctions.java
