### ISSUE TITLE
Development under progress ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [jphp-compiler/jphp#242]
Is this project under development  ?
Or stopped 

Please let me now .

I am  very excited to run php on jvm . PHP 7.2

**Comment by dim-s** [comment]
Project is under development, but I spend a lot of time on a project which depends on jphp - https://github.com/jphp-compiler/develnext.

**Comment by dim-s** [comment]
I have no plan to implement the PHP 7+ language features in the near future. Maybe 2018 year...
