### ISSUE TITLE
Поддержка PHP 7.1

### ISSUE THREAD

**Issue by nagayev** [jphp-compiler/jphp#243]
Здравстуйте.
Скоро ли будет добавлена поддержка PHP 7.1?

**Comment by artemirq** [comment]
Мне кажется, разработчику было бы интересно, какие именно плюшки из 7.1 тебе нужны

**Comment by MWStudio** [comment]
Всё уже добавили кроме ананимных функций

**Comment by dim-s** [comment]
@MWStudio анонимных классов, а не функций.
