### ISSUE TITLE
Разный вывод строки двумя способами

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/jphp#245]
$codedString = str::encode('Моя строка 1, My string 1', 'UTF-8');
        
        foreach (str_split($codedString) as $char) {
            var_dump($char);
        }
        var_dump('---------------------------------------------');
        for ($i = 0; $i < strlen($codedString); $i++) {
            var_dump($codedString[$i]);
        }
Ожидал одинаковый вывод...
Что вывело https://pastebin.com/7ZDWvh6j

**Comment by dim-s** [comment]
@artemirq encode() возвращает бинарную строку, а str_split ожидает родную юникодную строку, а не бинарную. Отсюда и потеря данных. Это не баг.

С бинарными строками нельзя работать как с обычными, это чревато такими проблемами, они годятся только для записи в stream'ы например.
