### ISSUE TITLE
Ошибка при запуске sanbox-android

### ISSUE THREAD

**Issue by HackMemory** [jphp-compiler/jphp#251]
Недавно увидел тут, что добавился sandbox-android, решил его собрать. Все вроде нормально собралось, но при запуске уже самого приложения выбивает ошибку. В logcat посмотрел, пишет это:

`E/AndroidRuntime( 9831): FATAL EXCEPTION: main
E/AndroidRuntime( 9831): Process: org.develnext.sandbox, PID: 9831
E/AndroidRuntime( 9831): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.develnext.sandbox/org.develnext.sandbox.AppActivity}: java.lang.ClassNotFoundException: Didn't find class "org.develnext.sandbox.AppActivity" on path: DexPathList[[zip file "/data/app/org.develnext.sandbox-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.develnext.sandbox-1, /vendor/lib, /system/lib]]`

Почему так происходит? Либо еще ничего не готово, и из-за этого выбивает эту ошибку?

**Comment by dim-s** [comment]
@HackMemory надо использовать проект из develnext репозитория https://github.com/jphp-compiler/develnext/tree/story208-android-jfx/sandbox-android (ветка story208-android-jfx).

**Comment by HackMemory** [comment]
Понял почему не собиралось, но не суть.
Теперь попробовал уже эту собрать, тоже ошибка при запуске:
`E/AndroidRuntime( 2614): FATAL EXCEPTION: main
E/AndroidRuntime( 2614): Process: org.develnext.jphp.ext.android, PID: 2614
E/AndroidRuntime( 2614): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.develnext.jphp.ext.android/javafxports.android.FXActivity}: android.view.InflateException: Binary XML file line #20: Error inflating class com.android.internal.policy.impl.RecentApplicationsBackground
E/AndroidRuntime( 2614):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
E/AndroidRuntime( 2614):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
E/AndroidRuntime( 2614):        at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 2614):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 2614):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2614):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2614):        at android.app.ActivityThread.main(ActivityThread.java:5019)
E/AndroidRuntime( 2614):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2614):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2614):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2614):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2614):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2614): Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.android.internal.policy.impl.RecentApplicationsBackground
E/AndroidRuntime( 2614):        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime( 2614):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime( 2614):        at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
E/AndroidRuntime( 2614):        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 2614):        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 2614):        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3022)
E/AndroidRuntime( 2614):        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085)
E/AndroidRuntime( 2614):        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:305)
E/AndroidRuntime( 2614):        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:299)
E/AndroidRuntime( 2614):        at android.app.Activity.setContentView(Activity.java:1949)
E/AndroidRuntime( 2614):        at javafxports.android.FXActivity.onCreate(FXActivity.java:111)
E/AndroidRuntime( 2614):        at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 2614):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
E/AndroidRuntime( 2614):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
E/AndroidRuntime( 2614):        ... 11 more
E/AndroidRuntime( 2614): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2614):        at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 2614):        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime( 2614):        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime( 2614):        ... 24 more`

**Comment by dim-s** [comment]
@HackMemory Какой командой ты собираешь?, я тестировал на версии андроида 4.4.4.

**Comment by HackMemory** [comment]
Да, jphp последняя, ставил сегодня.
Собираю такой командой:
`gradlew android`

**Comment by dim-s** [comment]
Попробуй подключить android устройство через usb и командой `androidInstall` установить приложение, оно появится в списке, без иконки.

**Comment by HackMemory** [comment]
Увы, но так я уже делал и все равно ничего не получалось.
Ну попробую вообще по новой. Может что то не так делал

**Comment by HackMemory** [comment]
Возможно из-за этого у меня ошибки. Когда я собирал первый его, у меня появлялись странные ошибки, что вроде такого, `Duplicate files copied in ...`
Добавил эти строки сюда, скрин: http://prntscr.com/gyjp5x
И вроде все без ошибок собиралось. Но может быть это причиной?

**Comment by HackMemory** [comment]
Возможно из-за этого у меня ошибки. Когда я собирал первый раз его, у меня появлялись странные ошибки, что вроде такого,  `Duplicate files copied in APK ...`
Добавил эти строки сюда, скрин: http://prntscr.com/gyjp5x
И вроде все без ошибок собиралось. Но может быть это причиной?

**Comment by dim-s** [comment]
Вполне возможно конечно, главное чтобы запускалось.

**Comment by HackMemory** [comment]
Пересобрал все с нуля и какая та магия, все сработало :D
